name = "gosee"
from = "base"

version = '70e164e755f8a5eb7ce683ec8ae65cf9eaf2c3c1'

devDependencies = ["clone", "go"]

build = """
clone --https --shallow --ref={{VERSION}} https://github.com/jmbaur/gosee
cd /root/src/github.com/jmbaur/gosee
go build -o /usr/local/bin/gosee
rm -r /root/src
"""

exports = ["/usr/local/bin/gosee"]

[checkUpdates]
type = "github-commit"
url = "https://github.com/jmbaur/gosee"
